# Generated by Django 5.2.16 on 2026-08-02 14:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('organizations', '0001_initial'),
        ('rules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fingerprint', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Baixo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Critico')], max_length=20)),
                ('status', models.CharField(choices=[('new', 'Novo'), ('valid', 'Valido'), ('false_positive', 'Falso positivo'), ('resolved', 'Resolvido')], default='new', max_length=20)),
                ('recommended_action', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('rule_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='rules.rulerun')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AlertEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='alerts.alert')),
                ('invoice_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alert_evidence', to='invoices.invoicerecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AlertStatusEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(choices=[('new', 'Novo'), ('valid', 'Valido'), ('false_positive', 'Falso positivo'), ('resolved', 'Resolvido')], max_length=20)),
                ('to_status', models.CharField(choices=[('new', 'Novo'), ('valid', 'Valido'), ('false_positive', 'Falso positivo'), ('resolved', 'Resolvido')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='alerts.alert')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_status_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(fields=('rule_run', 'fingerprint'), name='uniq_alert_run_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='alertevidence',
            constraint=models.UniqueConstraint(fields=('alert', 'invoice_record'), name='uniq_alert_invoice_evidence'),
        ),
    ]
