# Generated by Django 5.2.16 on 2026-08-02 14:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_row_number', models.PositiveIntegerField()),
                ('supplier_identifier', models.CharField(max_length=120)),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('invoice_number', models.CharField(max_length=120)),
                ('normalized_invoice_number', models.CharField(max_length=120)),
                ('invoice_date', models.DateField()),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='A moeda deve usar um codigo ISO com tres letras maiusculas.', regex='^[A-Z]{3}$')])),
                ('source_values', models.JSONField(blank=True, default=dict)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_records', to='imports.importbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ('source_row_number',),
                'indexes': [models.Index(fields=['organization', 'supplier_identifier', 'normalized_invoice_number'], name='invoice_duplicate_lookup_idx')],
                'constraints': [models.UniqueConstraint(fields=('import_batch', 'source_row_number'), name='uniq_invoice_import_source_row')],
            },
        ),
    ]
