# Generated by Django 5.2.16 on 2026-08-02 14:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('storage_key', models.CharField(blank=True, max_length=500)),
                ('file_sha256', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(64), django.core.validators.RegexValidator(message='O hash deve ser um SHA-256 hexadecimal em minusculas.', regex='^[0-9a-f]{64}$')])),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Em processamento'), ('completed', 'Concluida'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('column_mapping', models.JSONField(blank=True, default=dict)),
                ('error_summary', models.JSONField(blank=True, default=list)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('valid_row_count', models.PositiveIntegerField(default=0)),
                ('invalid_row_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('organization', 'file_sha256'), name='uniq_import_org_file_hash'), models.CheckConstraint(condition=models.Q(('row_count__gte', 0)), name='import_row_count_nonnegative'), models.CheckConstraint(condition=models.Q(('valid_row_count__gte', 0)), name='import_valid_count_nonnegative'), models.CheckConstraint(condition=models.Q(('invalid_row_count__gte', 0)), name='import_invalid_count_nonnegative')],
            },
        ),
    ]
