# Generated by Django 5.2.16 on 2026-08-02 14:09

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imports', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='A chave deve usar letras maiusculas, numeros e underscores.', regex='^[A-Z][A-Z0-9_]*$')])),
                ('version', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('default_severity', models.CharField(choices=[('low', 'Baixo'), ('medium', 'Medio'), ('high', 'Alto'), ('critical', 'Critico')], max_length=20)),
                ('parameters_schema', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('key', '-version'),
                'constraints': [models.UniqueConstraint(fields=('key', 'version'), name='uniq_rule_key_version'), models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='rule_version_positive')],
            },
        ),
        migrations.CreateModel(
            name='RuleRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em execucao'), ('completed', 'Concluida'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('alert_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_runs', to='imports.importbatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('rule_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='rules.ruledefinition')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('alert_count__gte', 0)), name='rule_run_alert_count_nonnegative')],
            },
        ),
    ]
