# Generated by Django 5.2.16 on 2026-08-02 17:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlScenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='A chave deve usar letras maiúsculas, números e underscores.', regex='^[A-Z][A-Z0-9_]*$')])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
            ],
            options={
                'ordering': ('key',),
            },
        ),
        migrations.CreateModel(
            name='ControlScenarioVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('draft', 'Rascunho'), ('approved', 'Aprovada')], default='draft', max_length=20)),
                ('organization_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('objective', models.JSONField(blank=True, default=dict)),
                ('risk', models.JSONField(blank=True, default=dict)),
                ('control', models.JSONField(blank=True, default=dict)),
                ('monitoring', models.JSONField(blank=True, default=dict)),
                ('rules', models.JSONField(blank=True, default=list)),
                ('limitations', models.JSONField(blank=True, default=list)),
                ('created_by_email', models.EmailField(max_length=254)),
                ('created_by_user_id', models.UUIDField()),
                ('created_by_role', models.CharField(choices=[('owner', 'Proprietário'), ('analyst', 'Analista')], max_length=20)),
                ('approved_by_email', models.EmailField(blank=True, max_length=254)),
                ('approved_by_user_id', models.UUIDField(blank=True, null=True)),
                ('approved_by_role', models.CharField(blank=True, choices=[('owner', 'Proprietário')], max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('approval_note', models.TextField(blank=True)),
                ('change_reason', models.TextField()),
                ('config_hash', models.CharField(blank=True, max_length=64, validators=[django.core.validators.MinLengthValidator(64), django.core.validators.RegexValidator(message='O hash deve ser um SHA-256 hexadecimal em minúsculas.', regex='^[0-9a-f]{64}$')])),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_control_scenario_versions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_control_scenario_versions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='organizations.organization')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='control_scenarios.controlscenario')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by_versions', to='control_scenarios.controlscenarioversion')),
            ],
            options={
                'ordering': ('scenario__key', '-version'),
            },
        ),
        migrations.AddField(
            model_name='controlscenario',
            name='active_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_scenarios', to='control_scenarios.controlscenarioversion'),
        ),
        migrations.AddConstraint(
            model_name='controlscenarioversion',
            constraint=models.UniqueConstraint(fields=('scenario', 'version'), name='uniq_control_scenario_version'),
        ),
        migrations.AddConstraint(
            model_name='controlscenarioversion',
            constraint=models.UniqueConstraint(condition=models.Q(('supersedes__isnull', False)), fields=('supersedes',), name='uniq_control_scenario_superseder'),
        ),
        migrations.AddConstraint(
            model_name='controlscenarioversion',
            constraint=models.CheckConstraint(condition=models.Q(('version__gte', 1)), name='control_scenario_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='controlscenarioversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('created_by_email', ''), _negated=True), ('created_by_role__in', ('owner', 'analyst')), models.Q(('organization_name', ''), _negated=True), models.Q(('name', ''), _negated=True), models.Q(('description', ''), _negated=True), models.Q(('change_reason', ''), _negated=True)), name='control_scenario_required_snapshots'),
        ),
        migrations.AddConstraint(
            model_name='controlscenarioversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('approval_note', ''), ('approved_at__isnull', True), ('approved_by_email', ''), ('approved_by_role', ''), ('approved_by_user_id__isnull', True), ('config_hash', ''), ('effective_from__isnull', True), ('state', 'draft')), models.Q(('approved_at__isnull', False), ('approved_by_role', 'owner'), ('approved_by_user_id__isnull', False), ('effective_from__isnull', False), ('state', 'approved'), models.Q(('approved_by_email', ''), _negated=True), models.Q(('approval_note', ''), _negated=True), models.Q(('config_hash', ''), _negated=True)), _connector='OR'), name='control_scenario_approval_consistent'),
        ),
        migrations.AddConstraint(
            model_name='controlscenario',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='uniq_control_scenario_org_key'),
        ),
    ]
